# Generated by Django 5.1.4 on 2024-12-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='moviereview',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='moviereview',
            name='updated_at',
        ),
    ]
